### ISSUE TITLE
Not running sync

### ISSUE THREAD

**Issue by borja190898** [cmathews393/spotify-to-plex#32]
2024-07-13 13:56:29.024 | DEBUG    | spotiplex.modules.spotiplex.main:process_pla
ylist:110 - Error processing playlist 'ID_HIDED': Invalid library section: Music                                                                    
Whats happening? thanks!

**Comment by cmathews393** [comment]
Not enough context. Please include how you're running the script (Docker/Python), whether you're on the latest version, whether you're syncing from Lidarr or manual lists, etc.
